### ISSUE TITLE
Ordering function cannot be used with 'as'

### ISSUE THREAD

**Issue by dirknilius** [rzane/baby_squeel#13]
I'm migrating from `squeel` to `baby-squeel` and found a case which worked fine in `squeel` but not in `baby-squeel`. `selecting` an virtual column with `as` syntax cannot be used for `ordering`.

Example:
```ruby
SomeTable.selecting { ['*', (some_date < 8.days.ago).as('long_standing')] }.ordering { [title.desc, long_standing.desc] }
```

This works in `squeel`:
```ruby
SomeTable.select { ['*', (some_date < 8.days.ago).as(long_standing)] }.order { [title.desc, `long_standing`.desc] }
```

This produces:
```
There is no column or association named 'long_standing' for SomeTable
```

Would be great to have this feature :-)

**Comment by rzane** [comment]
I think this would get the job done:

```ruby
SomeTable.selecting { ['*', (some_date < 8.days.ago).as('long_standing')] }
         .ordering { [title.desc, sql('long_standing').desc] }
```

Squeel uses backticks as a shorthand for `Arel::Nodes::SqlLiteral`. BabySqueel offers the `sql` method for this.

**Comment by dirknilius** [comment]
@rzane Allright, this works :) Maybe you want to add this to the docs.

**Comment by rzane** [comment]
Yes, I definitely will. Thank you for inquiring!

**Comment by rzane** [comment]
For more info, see: https://github.com/rzane/baby_squeel#helpers
