### ISSUE TITLE
Ignoring multiple joins

### ISSUE THREAD

**Issue by kbaum** [rzane/baby_squeel#16]
Squeel allowed for stuff like this:

```ruby
scope = scope.joins{dog}.where{dog.name = my{name}} if name.present?
scope = scope.joins{dog}.where{dog.breed = my{breed}} if breed.present?
```
In the above example, if name and breed is present, dog will be joined twice.  Squeel just ignores the second join of dog while baby_squeel raises an error.

**Comment by rzane** [comment]
I think the problem here is that you're using symbols. BabySqueel doesn't support that.

```ruby
scope = scope.joins{dog}.where{dog.name = my{name}} if name.present?
scope = scope.joins{dog}.where{dog.breed = my{breed}} if breed.present?
```

**Comment by kbaum** [comment]
Apologize.. the symbols was just a typo.  I am updating the example.

**Comment by rzane** [comment]
I'm having trouble reproducing your issue. I tried to test your explanation as best I could here:
https://gist.github.com/rzane/2a331dad471e8a299a5da8d0a6ec80bc

Could you try to provide me with a reproduction case based off of that gist?

Also, note that there is a spec for this behavior. See: https://github.com/rzane/baby_squeel/blob/57258fdbbed0f9c84c63108686215b9aa78eed61/spec/integration/joining_spec.rb#L250

**Comment by rzane** [comment]
Hi @kbaum, I'm still unable to reproduce this issue. If this is a bug, I'd really like to track it down.

**Comment by Schwad** [comment]
Hey, since I'm in the middle of Rails 5 upgrade / migrating from Squeel to Baby Squeel, I might be getting errors relatively similar to this in some spots. If I do, I'll try to post the info here. If it's not related, hopefully @kbaum will let us know.

**Comment by rzane** [comment]
Thanks @Schwad!
