### ISSUE TITLE
Better support for EXISTS subqueries

### ISSUE THREAD

**Issue by chewi** [rzane/baby_squeel#25]
Hello! In Squeel, I used to be able to do this.

```ruby
Customer.where{NOT EXISTS PageAction.where{customer_id == customers.id}}
```

Now I've had to change it to this.

```ruby
Customer.where.has{NOT EXISTS PageAction.where.has{customer_id == Customer.arel_table[:id]}.arel.ast}
```

The `arel_table` bit probably only works thanks to a patch I've made against ActiveRecord though I haven't tried without. The Squeel syntax no longer works because Baby Squeel complains that `customers` is not a valid column or association. I wonder if there's a way for Baby Squeel to realise this is a subquery. Probably not but worth considering!

The `arel.ast` bit was not necessary in Squeel thanks to activerecord-hackery/squeel@1ce36015b31a7753726372c82512a03d6327d68f. I'm not sure if it's possible to do this in Baby Squeel due to its non-invasive approach but it would be nice. Note that `arel` is sufficient for finds but `arel.ast` is needed for counts.

P.S. I had a fix for bind values in joins but by the time I hit the Pull Request button, you'd already pushed a fix to master! :laughing:

**Comment by rzane** [comment]
That's for the feedback. I totally forgot about EXISTS. #26 should fix this.

You're right that you can't reference tables without an association with BabySqueel, however, you can do this:

```ruby
where.has { customer_id == BabySqueel[:customers].id }
```

And, thanks for trying the PR, I sincerely appreciate any and all contributions!
