### ISSUE TITLE
Grouping function

### ISSUE THREAD

**Issue by odedniv** [rzane/baby_squeel#30]
In squeel you have the `_` function in the DSL, which lets you convert certain native objects to a usable object in squeel. It also adds brackets around the item in the SQL.

Hard to explain, here's examples:

```ruby
# Subquery in SELECT
User.select{_(Post.where{user_id == users.id}.select{COUNT(id)}).as('post_count')}
# => SELECT (SELECT COUNT(posts.id) FROM posts WHERE posts.user_id = users.id) AS post_count FROM users

# Array IN (subquery)
User.where{_([x, y]).in(Post.select{[x, y]})}
# => SELECT users.* FROM users WHERE (users.x, users.y) IN (SELECT posts.x, posts.y FROM posts)
```

As you can see, this is useful in certain occasions, and I cannot find a way to work around it.

You can find squeel's implementation here: https://github.com/activerecord-hackery/squeel/blob/master/lib/squeel/dsl.rb#L79

**Comment by rzane** [comment]
Closed by #32
