### ISSUE TITLE
Using BETWEEN condition?

### ISSUE THREAD

**Issue by hrasguido** [rzane/baby_squeel#59]
Is there anyway to write BETWEEN condition?

**Comment by rzane** [comment]
Yup. It would look like this:

```ruby
Post.where.has { created_at.between 1.hour.ago..3.days.from_now }
```

This document is pretty useful: http://www.rubydoc.info/github/rails/arel/Arel/Attributes/Attribute. In the example above, `created_at` is just a wrapper around `Arel::Attributes::Attribute`.

**Comment by hrasguido** [comment]
thanks!
