### ISSUE TITLE
problems with where.has on associations

### ISSUE THREAD

**Issue by dchersey** [rzane/baby_squeel#72]
With squeel I am able to say `user.posts.where {posted == 1} `

With baby_squeel it looks like I have to say `User.where.has {|p| (p.posted == 1) & (p.user_id = user.id) }`

Is there any other way to do a query using an association relationship? 

Thank you!

**Comment by rzane** [comment]
I'm not sure I understand the problem here. You can definitely query on associations in baby squeel. Are you getting an error of some kind? Perhaps you could better demonstrate the issue by filling out the github issue template.

**Comment by dchersey** [comment]
Hmmm.. ok, it seemed to me that it was unsupported. Here's what I am doing: 

I have a relationship from User to Activity as follows: 
```ruby
has_many :initiated_activity, class_name: 'Activity', inverse_of: :initiator, foreign_key: 'initiator_id', dependent: :nullify
  has_many :received_activity, class_name: 'Activity', inverse_of: :receiver, foreign_key: 'receiver_id', dependent: :nullify
```

when I run `User.first.initiated_activity.where.has {|a| a.receiver == User.last}.count`
I get
```
  User Load (0.4ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
  User Load (0.4ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
  User Load (0.3ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
  User Load (0.3ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
RuntimeError: unsupported: FalseClass
from /Users/david/projects/caring-economy/vendor/ruby/2.3.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:735:in `unsupported'
```

without the `.count` I get 
```
#<Activity::ActiveRecord_AssociationRelation:0x3fe55438daf0>
```

When I query by the foreign key specifically, i.e. `User.first.initiated_activity.where.has {|a| a.receiver_id == User.last.id}.count then I do get a query result 

```ruby
User.first.initiated_activity.where.has {|a| a.receiver_id == User.first.id}.count
  User Load (0.4ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
  User Load (0.4ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
  User Load (0.2ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
  User Load (0.2ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
   (0.1ms)  SELECT COUNT(*) FROM "activities" WHERE "activities"."initiator_id" = $1 AND "activities"."receiver_id" = 1  [["initiator_id", 1]]
   (0.1ms)  SELECT COUNT(*) FROM "activities" WHERE "activities"."initiator_id" = $1 AND "activities"."receiver_id" = 1  [["initiator_id", 1]]
=> 12
```
I am not clear why this query is executing multiple times, and also not clear why I have to specify the foreign key ... does this make sense?

**Comment by rzane** [comment]
I'm pretty sure you're on an old version of Baby Squeel, but I'm really just taking stabs in the dark here, because you didn't fill out the [issue template](https://github.com/rzane/baby_squeel/blob/master/ISSUE_TEMPLATE.md).

This functionality was added in version 1.0.2. Tests for it are [here](https://github.com/rzane/baby_squeel/blob/08ec8492e50335b5cfa79c44d6fc0a669b16e25f/spec/integration/where_chain_spec.rb#L281-L311).

Please upgrade to the latest version. If that doesn't work, please make a test case based off of the issue template.

**Comment by dchersey** [comment]
Ahh, that explains it.  Updated to 1.1.5 and now I am getting an explanation:
```
BabySqueel::AssociationComparisonNotSupportedError: Querying association 'receiver' with '==' and '!=' is only supported for ActiveRecord >=5
```

I'm still on Rails 4.2, so I guess I'll have to use the ID for now; migrating to baby_squeel was part of the Rails 5 prep.

Thanks for your help :)

**Comment by rzane** [comment]
Yeah, sorry. It was relatively easy to support in 5+, but would have been a lot of code to support in 4. Glad you figured it out!
