### ISSUE TITLE
Migration from squeel

### ISSUE THREAD

**Issue by brunobrgs** [rzane/baby_squeel#74]
```ruby
# Using squeel
City.where { state_id.in(State.all) }.to_sql
=> "SELECT `cities`.* FROM `cities`  WHERE `cities`.`state_id` IN (SELECT `states`.`id` FROM `states`)"

# Using baby_squeel
City.where { state_id.in(State.all) }.to_sql
=> "SELECT `cities`.* FROM `cities` WHERE `cities`.`state_id` IN (SELECT `states`.* FROM `states`)"
```
I have this kind of problem spread throughout my application, i am migrating and also using the `compatibility mode` .

Is there a way to get this same behavior back?

**Comment by rzane** [comment]
The easy solution is to just say `state_id.in(State.select(:id))`.

**Comment by brunobrgs** [comment]
Yes, thanks
I was just imagining if there was not a way to just keep it working in the old way.
With this change, i will need to change a lot of places.

**Comment by rzane** [comment]
Yeah, sorry :(
