### ISSUE TITLE
Multiple on conditions

### ISSUE THREAD

**Issue by octavpo** [rzane/baby_squeel#78]
I need to write something like this:
```
Assignment.joining{student_assignments.outer.on(student_assignments.assignment_id == id).
  on(student && student_assignments.student_id == student.id)}
```
where the first `on` is the normal association condition, and the second `on` is an optional condition, which should be added only when local variable `student` is defined.

It almost works but not quite. If `student` is nil then the first `on` condition is generated as expected. If `student` is defined, then the second `on` condition replaces the first one rather than being added to it. I tried to write both conditions in a single `on` like:
```
Assignment.joining{student_assignments.outer.on((student_assignments.assignment_id == id) & 
  (student && student_assignments.student_id == student.id))}
```
and then it works fine when `student` is defined, but I get an error about an 'Unsupported argument type: NilClass' when `student` is nil (not surprisingly). Is there a way to make it work? Thanks.

**Comment by rzane** [comment]
I think you just need to provide one `on` condition.

```ruby
Assignment.joining do
  expr = student_assignments.assignment_id == id
  expr &= student_assignments.student_id == student.id if student
  student_assignments.outer.on(expr)
end
```

**Comment by octavpo** [comment]
Yes that works fine, thanks. However it doesn't look great for chaining with all other clauses in the query, even if I use `{}` instead of `do ... end`. Is there some kind of 'empty' node I can use that `&` recognizes so it doesn't generate anything for it? Then I could write the second term for `&` like:
```
(student ? (student_assignments.student_id == student.id) : empty)
```
Thanks.

**Comment by octavpo** [comment]
I know I could use `sql('TRUE')`, but that actually generates `AND TRUE`, I'd prefer to avoid that. Thanks.

**Comment by rzane** [comment]
Maybe instead of building a giant chaining query, you should take advantage of scopes.

```ruby
class Assessment < ApplicationRecord
  def self.with_student_assignments
    joining do
      expr = student_assignments.assignment_id == id
      expr &= student_assignments.student_id == student.id if student
      student_assignments.outer.on(expr)
    end
  end
end

# then you can say:
Assessment.with_student_assessments.where.has { ... }
```

**Comment by octavpo** [comment]
That is part of a scope called `with_completion_data` actually, it's not that giant, it adds a `selecting` and a `grouping`. I'm not going to write a separate scope for each single function in a query, it's better to split them by the program logic. It also writes on 7 lines what I could write on one or two. Still it would be useful to have an empty node.
