### ISSUE TITLE
Accessing the model table on associations

### ISSUE THREAD

**Issue by octavpo** [rzane/baby_squeel#79]
I have a model called `Asset`, which has an association that was expressed in squeel like:
```
has_many :using_problems,
    -> {where{assets.asset_locator =~ concat('%', ~problem_file)}},
    source: :problems
```
When I try something similar in baby_squeel, it complains:
```
BabySqueel::NotFoundError (There is no function or column or association named 'assets' for Problem.):
```
Is there any other way I can reference the model table in an association in baby_squeel? Thanks.

**Comment by rzane** [comment]
I'm going to need a lot more information than what you've given. I need to know:
* What Active Record version?
* What Baby Squeel version?
* What does your schema look like?
* What do your associations look like?
* What actual Baby Squeel code did you run? You've only shown Squeel examples.

If you fill our the issue template [here](https://github.com/rzane/baby_squeel/blob/master/ISSUE_TEMPLATE.md), I'll do my best to help you figure this out.

**Comment by octavpo** [comment]
Active Record 5.0.5, Baby Squeel 1.1.5. There's no other link between the two tables, the association is just what you see above. The baby_squeel code is just:
```
has_many :using_problems,
    -> {where.has{assets.asset_locator =~ concat('%', problem_file)}},
    source: :problems
```
I tried with `asset` instead of `assets`, still nothing. I think there should be a way to refer the current table, maybe through something like `self` or the table name. Thanks.

**Comment by rzane** [comment]
Right, but I'm not understanding how `assets` relates to `problems`. Are you joining this table?

**Comment by octavpo** [comment]
Well, the above can't be true, I mean there's no other direct link between the two tables. There is a link through another table: `Asset` does have a `belongs_to :package` and Package has a `has_many :problems`. And the `using_problems` specifies `through: :package`.

**Comment by rzane** [comment]
Maybe try`package.assets.asset_locator`? That's literally a guess, because I have no idea what you're trying to accomplish and I have no idea what your schema looks like. I really want to help, but I created the issue template for a reason. Please use it, or I can't help you.

**Comment by octavpo** [comment]
Yes I tried that, I'm getting an error:
```
NoMethodError (undefined method `arel' for #<ActiveRecord::QueryMethods::WhereChain:0x007f8d92a1fe10>):
```
But my point is that even if that worked, that's not the right answer. I think it's good that unlike squeel, baby_squeel checks the column names, but it only checks them agains one table and its associations/joins. And while that's fine in most cases, I think in case of defining associations both tables should be accessible, and not by relying on reverse relationships. So i was hoping you already have something, it seems you don't, so now I'm hoping you might consider adding a facility. Thanks.

**Comment by rzane** [comment]
So first of all, there is a way to do this:

```ruby
where.has { BabySqueel[Asset].asset_locator =~ concat('%', problem_file) }
```

But, this isn't going to give you table aliasing, so it's not the "ideal" solution.

I'm also about 95% certain there's a better way to handle this that exists in baby squeel. But, if you won't fill out the issue template and give me a way to reproduce your scenario, I'm not willing to dedicate any more of my time to this issue.

**Comment by octavpo** [comment]
Not sure how filling the template would help, looks like a waste of time. If you're just wondering why the previous example fails, sorry that was my fault, I forgot to add the `.has`. So yes the `package.assets.asset_locator` does work, but like I was saying it doesn't make sense to me to only be able to access the current model table through a chain of inverse associations. 
After more thought I think the right solution, also consistent with the rest of your package, would be to make the current table the one in scope, and let the associated table be accessed through the association name. So my example would look like:
```
has_many :using_problems,
    -> {where.has{asset_locator =~ concat('%', package.problems.problem_file)}},
    through: :package, source: :problems
```
or even better, if possible:
```
has_many :using_problems,
    -> {where.has{asset_locator =~ concat('%', using_problems.problem_file)}},
    through: :package, source: :problems
```
If you want to keep the current approach, I think you'd need a special way to access the current table, like maybe a `self.asset_locator`. Thanks.
