### ISSUE TITLE
Aliases don't work in 'on' and 'select' conditions

### ISSUE THREAD

**Issue by octavpo** [rzane/baby_squeel#81]
You have an example showing use of an alias in a join:
```
Post.joining { author.alias('a').on((author.id == author_id) | (author.name == title)) }
```
but an alias is useful if you can use it in conditions, like:
```
Post.joining { author.alias('a').on((a.id == author_id) | (a.name == title)) }
```
Does this work for you? I'm trying something similar and I'm getting an error about no column `a`. I also tried something like:
```
Post.joining { author.alias('a').on((sql('a').id == author_id) | (sql('a').name == title)) }
```
but that doesn't work either, it complains about undefined method for `id`. Is there a way to make this work? Thanks.

**Comment by rzane** [comment]
There's definitely no way to do this:

```ruby
Post.joining { author.alias('a').on((a.id == author_id) | (a.name == title)) }
```

Because there would be no way to define the `a` method like that. However, #77 is intended to address what you're talking about. You'd be able to say:

```ruby
Post.joining { |post| author.alias('a').on { (id == post.author_id) | (name == post.title) }
```

**Comment by octavpo** [comment]
This doesn't seem to be working for me. When I try:
```
Asset.joining{|asset| package.alias('p').on(id == asset.package_id)}.to_sql
```
I get an error:
```
NameError: undefined local variable or method `package' for main:Object
```
The no-arity form:
```
Asset.joining{package.alias('p').on(package.id == package_id)}.to_sql
```
works fine:
```
 => "SELECT `assets`.* FROM `assets` INNER JOIN `packages` `p` ON `packages`.`id` = `assets`.`package_id`" 
```
So I tried this:
```
Asset.joining{|asset| asset.package.alias('p').on(id == asset.package_id)}.to_sql
```
and then I got:
```
NameError: undefined local variable or method `id' for main:Object
```
The only way I could make it work is:
```
Asset.joining{|asset| asset.package.alias('p').on(asset.package.id == asset.package_id)}.to_sql
```
but then it solves nothing, as it generates the same query as the no-arity form. What I hope to get is:
```
 => "SELECT `assets`.* FROM `assets` INNER JOIN `packages` `p` ON `p`.`id` = `assets`.`package_id`" 
```

**Comment by rzane** [comment]
It should be:

```ruby
Asset.joining{ package.alias('p').on(package.id == package_id) }.to_sql
```

But, seriously, I can't predict the behavior of baby squeel without knowing your schema definition and the relationships between your models. Please stop submitting issues without the issue template. The intent of the issue template is to save ME time. Thanks.

**Comment by octavpo** [comment]
Are you serious? I'm not asking you to predict anything, I was asking a question about a feature that is not documented, so I wanted to know if it's supported or not. That template can be useful for bug reports that you can't reproduce. That's not what this is about. So the question is if baby_squeel supports using aliases in `on` or `where` queries. If it does, it's up to you to show how and provide an example, and it can be in any model you want. You gave me a potential 'solution':
```
Post.joining { |post| author.alias('a').on { (id == post.author_id) | (name == post.title) }
```
Please show me what sql this generates. Or if you have a better solution. Thanks.

**Comment by rzane** [comment]
All I'm asking for is to know your schema and your association definitions. Since this is a question, I don't need a test case. By giving me the schema and association definitions, I can run the code that I'm telling you will "probably" work and guarantee that it does work. I don't want to go back and forth with you guessing at the right solution and having you tell me that it doesn't work.

The code you've written in your previous comment is not currently supported. Like I said, there is a PR (#77) that adds that functionality. For now, you have to reference the alias explicitly:

```ruby
Post.joining { author.alias('a').on((author.alias('a').id == author_id) | (author.alias('a').name == title)) }
```

**Comment by octavpo** [comment]
Have you tested this? What sql query do you get? It's not working for me. Or better could you separate the changes for this feature from #77 and merge them? It seems #77 fails on an unrelated subquery issue. Thanks.
