### ISSUE TITLE
Rails 5.2 support

### ISSUE THREAD

**Issue by kylekermgard** [rzane/baby_squeel#85]
It looks like baby_squeel isn't working with joins in rails 5.2.0.beta2.

**Comment by rzane** [comment]
Yup, this is a top priority. I'll work on this ASAP.

**Comment by rzane** [comment]
Okay, I spend some time looking into this. It should be solvable, but it's going to take quite a bit more research. So far, I've identified the source of the changes that caused 5.2 to break:

* https://github.com/rails/rails/commit/8ad8bbaef8c4f521f292765a02ddb91e48160366#diff-bf6dd6226db3aab589916f09236881c7
* https://github.com/rails/rails/commit/c5ab6e51a7b9ee05a2d262a72c7130b9c1d1b0ce#diff-bf6dd6226db3aab589916f09236881c7
* https://github.com/rails/rails/commit/40cadf52db5e21349f6ecd9c4dc9b89d42ebc986#diff-bf6dd6226db3aab589916f09236881c7

**Comment by rzane** [comment]
I'm working on this in #87. It's really close!

**Comment by kapso** [comment]
`has_many` & `has_one` via `through` is breaking on Rails 5.2 because of this gem
